### PR TITLE
Change theme to something less 'red'

### PR DESCRIPTION
**Pull request by not7cd**
image

### CODE REVIEW

**Comment by LiquidLemon** [comment]
The domain changes make sense, although ideally, we'd have it defined as a variable (it's fine considering we're the only users and we're not planning to change the domain any time soon).

As far as the theme goes, which to my understanding you just got somewhere online, is just plain bad. The previous one was much better. My main issues with it are:
- URLs and the version are unreadable,
- the background is very dark, coupled with the dark blue it requires a lot of effort to read,
- the color scheme doesn't fit any of our other sites,
- the alerts look unchanged and don't fit with the rest of the site.

If you don't feel like making a custom theme I'd rather just see the old one back with just the domains changed.

**Comment by not7cd** [comment]
I guess we could go with basic bootstrap theme, until we don't have our own theme.

As for URL. Yes, we have variable in settings.py. I forgot about it, and did `grep sed` magic.

**Comment by not7cd** [comment]
image
image

**Comment by LiquidLemon** [comment]
Looks much better now, thanks

**Pull request merged**
